using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NIST.CVP.ACVTS.Libraries.Crypto.Common.Asymmetric.LMS.Native.Helpers;
using NIST.CVP.ACVTS.Libraries.Generation.Core;
using NIST.CVP.ACVTS.Libraries.Generation.Core.Async;
using NIST.CVP.ACVTS.Libraries.Math;
using NIST.CVP.ACVTS.Libraries.Oracle.Abstractions;
using NIST.CVP.ACVTS.Libraries.Oracle.Abstractions.ParameterTypes.Lms;
using NIST.CVP.ACVTS.Libraries.Oracle.Abstractions.ResultTypes;
using NLog;

namespace NIST.CVP.ACVTS.Libraries.Generation.LMS.SP800_208.SigGen;

public class TestCaseGeneratorAft : ITestCaseGeneratorWithPrep<TestGroup, TestCase>
{
    private readonly IOracle _oracle;
    private ShuffleQueue<int> _messageLengths;
    private ShuffleQueue<int> _q;
    
    public int NumberOfTestCasesToGenerate { get; private set; } = 10;

    public TestCaseGeneratorAft(IOracle oracle)
    {
        _oracle = oracle;
    }    
    
    public GenerateResponse PrepareGenerator(TestGroup group, bool isSample)
    {
        // For small trees, set the number of test cases to exhaust the tree for better Q comparisons
        var h = AttributesHelper.GetLmsAttribute(group.LmsMode).H;
        if (h == 5)
        {
            NumberOfTestCasesToGenerate = 32;
        }
        
        var messageLengths = new List<int>();
        messageLengths.AddRange(group.MessageLength.GetDomainMinMaxAsEnumerable());
        messageLengths.AddRange(group.MessageLength.GetRandomValues(_ => true, NumberOfTestCasesToGenerate - 2));
        
        _messageLengths = new ShuffleQueue<int>(messageLengths);
        _q = new ShuffleQueue<int>(Enumerable.Range(0, 32).ToList());
        
        return new GenerateResponse();
    }
    
    public async Task<TestCaseGenerateResponse<TestGroup, TestCase>> GenerateAsync(TestGroup group, bool isSample, int caseNo = -1)
    {
        var param = new LmsSignatureParameters
        {
            MessageLength = _messageLengths.Pop(),
            Q = _q.Pop()    // Q ensures that no leaf is used multiple times
        };

        try
        {
            TestCase testCase = null;
            LmsSignatureResult result = null;
            if (isSample)
            {
                // Rely on tree generated by the group
                param.LmsKeyPair = group.KeyPair;
                result = await _oracle.GetLmsSignatureCaseAsync(param);
                testCase = new TestCase { Message = result.Message, Signature = result.Signature, MessageLength = param.MessageLength };
            }
            else
            {
                // Rely on tree generated by the client
                result = await _oracle.GetDeferredLmsSignatureCaseAsync(param);
                testCase = new TestCase { Message = result.Message, MessageLength = param.MessageLength };
            }

            return new TestCaseGenerateResponse<TestGroup, TestCase>(testCase);
        }
        catch (Exception ex)
        {
            ThisLogger.Error(ex);
            return new TestCaseGenerateResponse<TestGroup, TestCase>($"Error generating case: {ex.Message}");
        }
    }
    
    private static ILogger ThisLogger => LogManager.GetCurrentClassLogger();
}
